import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:medireminder/data/models/food_instruction.dart';
import 'package:medireminder/data/models/medicine_frequency.dart';
import 'package:medireminder/data/models/medicine_schedule.dart';
import 'package:medireminder/services/export_service.dart';

import 'test_helpers.dart';

void main() {
  group('ExportService', () {
    test('exportToJson produces valid JSON with medicines', () async {
      final env = await TestEnv.create();
      await env.settings.setOnboardingDone(true);

      // Add a medicine.
      await env.medicineRepository.insert(
        makeMedicine(
          name: 'Aspirin',
          dosage: '1',
          dosageUnit: 'tablet',
          frequency: MedicineFrequency.daily,
          foodInstruction: FoodInstruction.after,
          schedules: const [
            MedicineSchedule(medicineId: 0, hour: 8, minute: 0),
          ],
        ),
      );

      final export = ExportService(
        medicineRepository: env.medicineRepository,
        doseRepository: env.doseRepository,
      );

      final json = await export.exportToJson();
      final data = jsonDecode(json) as Map<String, dynamic>;

      expect(data['version'], 1);
      expect(data['exportedAt'], isNotNull);
      expect(data['medicines'], isA<List>());
      expect((data['medicines'] as List).length, 1);

      final med = (data['medicines'] as List).first as Map<String, dynamic>;
      expect(med['name'], 'Aspirin');
      expect(med['dosage'], '1');
      expect(med['dosageUnit'], 'tablet');
      expect(med['foodInstruction'], 'after');
      expect(med['schedules'], isA<List>());
      expect((med['schedules'] as List).length, 1);
    });

    test('exportToJson includes dose history', () async {
      final env = await TestEnv.create();
      await env.settings.setOnboardingDone(true);
      await env.appState.init();

      // Create a medicine and generate doses.
      await env.appState.saveMedicine(
        makeMedicine(
          name: 'BP Tablet',
          schedules: const [
            MedicineSchedule(medicineId: 0, hour: 8, minute: 0),
          ],
        ),
      );

      final export = ExportService(
        medicineRepository: env.medicineRepository,
        doseRepository: env.doseRepository,
      );

      final json = await export.exportToJson();
      final data = jsonDecode(json) as Map<String, dynamic>;

      expect(data['doses'], isA<List>());
      // Doses are generated by the scheduler, so we should have at least one.
      final doses = data['doses'] as List;
      if (doses.isNotEmpty) {
        final dose = doses.first as Map<String, dynamic>;
        expect(dose['medicineId'], isNotNull);
        expect(dose['status'], isNotNull);
        expect(dose['scheduledAt'], isNotNull);
      }
    });
  });
}
